import { promises as fs } from "node:fs";
import * as path from "node:path";
import type {
  RunwiseCategory,
  RunwiseDoctorReport,
  RunwiseEvalCase,
  RunwiseFinding,
  RunwiseSeverity,
  RunwiseTraceReplaySummary
} from "@runwise/schemas";

export const RUNWISE_REPORT_JSON = "runwise-report.json";
export const RUNWISE_REPORT_MARKDOWN = "runwise-report.md";
export const RUNWISE_REPORT_HTML = "runwise-report.html";

export interface WriteDoctorReportsOptions {
  outputDir: string;
}

export interface WrittenDoctorReports {
  jsonPath: string;
  markdownPath: string;
  htmlPath: string;
}

interface ReportRenderOptions {
  cwd?: string;
  jsonPath?: string;
  markdownPath?: string;
  htmlPath?: string;
}

const SEVERITY_ORDER: RunwiseSeverity[] = [
  "critical",
  "high",
  "medium",
  "low",
  "info"
];

export async function writeDoctorReports(
  report: RunwiseDoctorReport,
  options: WriteDoctorReportsOptions
): Promise<WrittenDoctorReports> {
  return writeReportFiles(report, options.outputDir);
}

export async function writeReportFiles(
  report: RunwiseDoctorReport,
  outputDir: string
): Promise<WrittenDoctorReports> {
  await fs.mkdir(outputDir, { recursive: true });

  const cwd = path.dirname(outputDir);
  const jsonPath = path.join(outputDir, RUNWISE_REPORT_JSON);
  const markdownPath = path.join(outputDir, RUNWISE_REPORT_MARKDOWN);
  const htmlPath = path.join(outputDir, RUNWISE_REPORT_HTML);
  const renderOptions = { cwd, jsonPath, markdownPath, htmlPath };
  const reportWithFiles = withReportFiles(report, renderOptions);

  await fs.writeFile(jsonPath, `${renderJsonReport(reportWithFiles)}\n`, "utf8");
  await fs.writeFile(markdownPath, `${renderMarkdownReport(reportWithFiles, renderOptions)}\n`, "utf8");
  await fs.writeFile(htmlPath, `${renderHtmlReport(reportWithFiles, renderOptions)}\n`, "utf8");

  return {
    jsonPath,
    markdownPath,
    htmlPath
  };
}

export function renderJsonReport(report: RunwiseDoctorReport): string {
  return JSON.stringify(report, null, 2);
}

export function renderEvalCaseJson(evalCase: RunwiseEvalCase): string {
  return JSON.stringify(evalCase, null, 2);
}

export function renderEvalCaseYaml(evalCase: RunwiseEvalCase): string {
  return renderYamlValue(evalCase, 0);
}

export function renderEvalCaseMarkdown(evalCase: RunwiseEvalCase): string {
  const riskTagLines =
    evalCase.riskTags.length > 0
      ? evalCase.riskTags.map((tag) => `- ${escapeMarkdown(tag)}`)
      : ["- none"];
  const lines = [
    "# Runwise Eval Case",
    "",
    "## Summary / 摘要",
    "",
    `- Case ID: \`${evalCase.caseId}\``,
    `- Type: \`${evalCase.type}\``,
    `- Title: ${escapeMarkdown(evalCase.title)}`,
    `- 中文标题: ${escapeMarkdown(evalCase.titleZh)}`,
    `- Source trace: ${escapeMarkdown(evalCase.source.traceFile)}`,
    `- Run ID: \`${evalCase.source.runId}\``,
    `- Trace status: \`${evalCase.source.traceStatus}\``,
    "",
    "## Input / 输入",
    "",
    ...formatEvalInput(evalCase.input),
    "",
    "## Expected Behavior / 预期行为",
    "",
    ...formatBilingualList(evalCase.expectedBehavior, evalCase.expectedBehaviorZh),
    "",
    "## Must Not / 禁止行为",
    "",
    ...formatBilingualList(evalCase.mustNot, evalCase.mustNotZh),
    "",
    "## Assertions / 断言",
    "",
    ...formatEvalAssertions(evalCase),
    "",
    "## Risk Tags / 风险标签",
    "",
    ...riskTagLines,
    "",
    "Generated by Runwise."
  ];

  return lines.join("\n");
}

export function renderMarkdownReport(
  report: RunwiseDoctorReport,
  options: ReportRenderOptions = {}
): string {
  const lines = [
    "# Runwise Doctor Report",
    "",
    "Runwise helps you check AI agent projects before they go live.",
    "",
    "Runwise 帮你在 AI Agent 项目上线前先做一次本地检查。",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Generated | ${escapeMarkdown(report.generatedAt)} |`,
    `| Scanned path | ${escapeMarkdown(report.scannedPath)} |`,
    "| Mode | Public preview · local-first / 公开预览 · 本地优先 |",
    `| Overall score | ${report.summary.overallScore}/100 |`,
    "",
    "## Rule Summary",
    "",
    "| Rule status | Count |",
    "| --- | ---: |",
    `| Total | ${report.rules.total} |`,
    `| Passed | ${report.rules.passed} |`,
    `| Failed | ${report.rules.failed} |`,
    `| Not applicable | ${report.rules.notApplicable} |`,
    `| Blocking | ${report.rules.blocking} |`,
    "",
    "## Severity Summary",
    "",
    "| Severity | Count |",
    "| --- | ---: |",
    `| Critical | ${report.summary.critical} |`,
    `| High | ${report.summary.high} |`,
    `| Medium | ${report.summary.medium} |`,
    `| Low | ${report.summary.low} |`,
    `| Info | ${report.summary.info} |`,
    `| Blocking findings | ${report.rules.blocking} |`,
    "",
    "## Category Scores",
    "",
    ...formatCategoryScoresMarkdown(report.summary.categoryScores),
    "",
    "## Detected Ecosystems / 检测到的生态",
    "",
    ...formatIntegrationsMarkdown(report),
    "",
    "## What to fix first / 优先修复项",
    "",
    ...formatFixFirstMarkdown(report.findings),
    "",
    "## Findings"
  ];

  for (const severity of SEVERITY_ORDER) {
    const findings = getFindingsBySeverity(report.findings, severity);
    if (findings.length === 0) {
      continue;
    }

    lines.push("", `### ${capitalize(severity)}`);

    for (const finding of findings) {
      lines.push(...formatFindingMarkdown(finding));
    }
  }

  if (report.findings.length === 0) {
    lines.push("", "No findings. Keep the current readiness baseline healthy.");
  }

  lines.push(
    "",
    "## Report Files",
    "",
    `- JSON: \`${formatReportPath(options.cwd, options.jsonPath, report.reportFiles?.json ?? ".runwise/runwise-report.json")}\``,
    `- Markdown: \`${formatReportPath(options.cwd, options.markdownPath, report.reportFiles?.markdown ?? ".runwise/runwise-report.md")}\``,
    `- HTML: \`${formatReportPath(options.cwd, options.htmlPath, report.reportFiles?.html ?? ".runwise/runwise-report.html")}\``,
    "",
    "These files are generated locally and ignored by git by default.",
    "",
    "这些文件在本地生成，默认不会被 git 跟踪。"
  );

  return lines.join("\n");
}

export function renderTraceReplayMarkdown(summary: RunwiseTraceReplaySummary): string {
  const highCriticalRisk = summary.riskSummary.high + summary.riskSummary.critical;
  const lines = [
    "# Runwise Trace Replay",
    "",
    "## Summary / 摘要",
    "",
    `- Run ID: \`${summary.runId}\``,
    summary.name ? `- Name: ${escapeMarkdown(summary.name)}` : undefined,
    `- Status: \`${summary.status}\``,
    `- Started: ${summary.startedAt}`,
    `- Ended: ${summary.endedAt ?? "not recorded"}`,
    `- Total steps: ${summary.totalSteps}`,
    `- Total duration: ${formatDuration(summary.totalDurationMs)}`,
    `- Errors: ${summary.errors.count}`,
    `- High/Critical risk steps: ${highCriticalRisk}`,
    `- Approval requests: ${summary.approval.requests}`,
    `- Approval responses: ${summary.approval.responses}`,
    "",
    "## Timeline / 时间线",
    "",
    ...formatReplayTimeline(summary),
    "",
    "## Risk Review / 风险复盘",
    "",
    `- Critical: ${summary.riskSummary.critical}`,
    `- High: ${summary.riskSummary.high}`,
    `- Medium: ${summary.riskSummary.medium}`,
    `- Low: ${summary.riskSummary.low}`,
    `- None: ${summary.riskSummary.none}`,
    `- Missing approval for high-risk tool activity: ${summary.approval.missingApprovalForHighRisk ? "yes" : "no"}`,
    "",
    "## Errors / 错误",
    "",
    ...formatReplayErrors(summary),
    "",
    "## Recommendations / 建议",
    "",
    ...formatReplayRecommendations(summary),
    "",
    "## Source Trace / 源 Trace",
    "",
    `- ${escapeMarkdown(summary.traceFile)}`,
    "",
    "Generated by Runwise."
  ].filter((line): line is string => line !== undefined);

  return lines.join("\n");
}

export function renderHtmlReport(
  report: RunwiseDoctorReport,
  options: ReportRenderOptions = {}
): string {
  const fixFirst = getPriorityFindings(report.findings).slice(0, 5);
  const scoreBadge = `<span class="score"><strong>${report.summary.overallScore}</strong><span>/100</span></span>`;
  const headerMetrics = [
    renderMetric("Generated", report.generatedAt),
    renderMetric("Scanned path", report.scannedPath),
    renderMetric("Mode", "Public preview · local-first / 公开预览 · 本地优先"),
    renderMetric("Overall score", scoreBadge, false, "metric-score")
  ].join("\n");
  const scoreMetrics = [
    renderMetric("Overall", `${report.summary.overallScore}/100`, true, "metric-score"),
    renderMetric("Critical", String(report.summary.critical), true, "metric-critical"),
    renderMetric("High", String(report.summary.high), true, "metric-high"),
    renderMetric("Medium", String(report.summary.medium), true, "metric-medium"),
    renderMetric("Low", String(report.summary.low), true, "metric-low"),
    renderMetric("Info", String(report.summary.info), true, "metric-info"),
    renderMetric("Blocking", String(report.rules.blocking), true, "metric-critical")
  ].join("\n");
  const ruleMetrics = [
    renderMetric("Total rules", String(report.rules.total)),
    renderMetric("Passed", String(report.rules.passed), true, "metric-success"),
    renderMetric("Failed", String(report.rules.failed), true, "metric-high"),
    renderMetric("Not applicable", String(report.rules.notApplicable)),
    renderMetric("Blocking", String(report.rules.blocking), true, "metric-critical")
  ].join("\n");
  const fixFirstHtml =
    fixFirst.length > 0
      ? `<div class="finding-list">${fixFirst.map(renderFindingCard).join("\n")}</div>`
      : `<div class="empty-state">No blocking, critical, or high-priority findings were found. Review medium and low findings when you have time.<br>没有发现 blocking、critical 或 high 级别问题。你可以在有时间时继续查看 medium 和 low 级别建议。</div>`;
  const findingsHtml = renderFindingsBySeverity(report.findings);
  const integrationsHtml = renderIntegrations(report);
  const jsonReportPath = formatReportPath(
    options.cwd,
    options.jsonPath,
    report.reportFiles?.json ?? ".runwise/runwise-report.json"
  );
  const markdownReportPath = formatReportPath(
    options.cwd,
    options.markdownPath,
    report.reportFiles?.markdown ?? ".runwise/runwise-report.md"
  );
  const htmlReportPath = formatReportPath(
    options.cwd,
    options.htmlPath,
    report.reportFiles?.html ?? ".runwise/runwise-report.html"
  );

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Runwise Doctor Report</title>
  <style>
    :root {
      color-scheme: light dark;
      --bg: #f7f7f3;
      --panel: #ffffff;
      --text: #191a17;
      --muted: #62665f;
      --border: #d9ddd2;
      --accent: #0f766e;
      --accent-soft: #d9f2ee;
      --critical: #b42318;
      --high: #c2410c;
      --medium: #b7791f;
      --low: #2563eb;
      --info: #4b5563;
      --success: #15803d;
      --shadow: 0 18px 50px rgba(20, 24, 18, 0.08);
    }

    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #11130f;
        --panel: #1a1d17;
        --text: #f3f4ef;
        --muted: #b7bcae;
        --border: #33382e;
        --accent: #5eead4;
        --accent-soft: #133936;
        --shadow: 0 18px 50px rgba(0, 0, 0, 0.35);
      }
    }

    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.5;
    }
    main {
      max-width: 1160px;
      margin: 0 auto;
      padding: 40px 20px 56px;
    }
    header {
      padding: 32px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel);
      box-shadow: var(--shadow);
    }
    h1, h2, h3, p { margin-top: 0; }
    h1 { margin-bottom: 8px; font-size: clamp(2rem, 5vw, 4rem); line-height: 1; letter-spacing: 0; }
    h2 { margin: 32px 0 16px; font-size: 1.35rem; }
    h3 { margin-bottom: 10px; font-size: 1rem; }
    .tagline { color: var(--muted); max-width: 780px; margin-bottom: 6px; }
    .meta-grid, .metric-grid, .category-grid, .rule-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
      gap: 12px;
    }
    .meta-grid { margin-top: 24px; }
    .metric, .finding, .empty-state {
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel);
      padding: 16px;
    }
    .metric-score { border-color: color-mix(in srgb, var(--accent), var(--border) 58%); }
    .metric-success { border-color: color-mix(in srgb, var(--success), var(--border) 60%); }
    .metric-critical { border-color: color-mix(in srgb, var(--critical), var(--border) 62%); }
    .metric-high { border-color: color-mix(in srgb, var(--high), var(--border) 62%); }
    .metric-medium { border-color: color-mix(in srgb, var(--medium), var(--border) 64%); }
    .metric-low { border-color: color-mix(in srgb, var(--low), var(--border) 64%); }
    .metric-info { border-color: color-mix(in srgb, var(--info), var(--border) 70%); }
    .metric-score .metric-value { color: var(--accent); }
    .metric-success .metric-value { color: var(--success); }
    .metric-critical .metric-value { color: var(--critical); }
    .metric-high .metric-value { color: var(--high); }
    .metric-medium .metric-value { color: var(--medium); }
    .metric-low .metric-value { color: var(--low); }
    .metric-info .metric-value { color: var(--info); }
    .metric-label { color: var(--muted); font-size: 0.82rem; text-transform: uppercase; letter-spacing: 0.04em; }
    .metric-value { margin-top: 4px; font-size: 1.45rem; font-weight: 750; overflow-wrap: anywhere; }
    .score {
      display: inline-flex;
      align-items: baseline;
      gap: 6px;
      color: var(--accent);
    }
    .score strong { font-size: clamp(2.4rem, 8vw, 5rem); line-height: 1; }
    .score span { color: var(--muted); font-size: 1.1rem; }
    .section {
      margin-top: 22px;
      padding: 24px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: rgba(255, 255, 255, 0.42);
    }
    @media (prefers-color-scheme: dark) {
      .section { background: rgba(255, 255, 255, 0.025); }
    }
    .finding-list { display: grid; gap: 12px; }
    .finding-head {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      align-items: center;
      margin-bottom: 12px;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      border: 1px solid var(--border);
      border-radius: 999px;
      padding: 3px 9px;
      font-size: 0.78rem;
      font-weight: 700;
      text-transform: uppercase;
    }
    .badge-critical { color: var(--critical); }
    .badge-high { color: var(--high); }
    .badge-medium { color: var(--medium); }
    .badge-low { color: var(--low); }
    .badge-info { color: var(--info); }
    .badge-blocking { color: var(--critical); background: rgba(180, 35, 24, 0.08); }
    .detail { color: var(--muted); }
    .finding-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
      gap: 12px;
      margin-top: 12px;
    }
    .finding-grid p { margin-bottom: 8px; }
    code {
      padding: 2px 5px;
      border-radius: 5px;
      background: var(--accent-soft);
      color: var(--text);
      overflow-wrap: anywhere;
    }
    footer {
      margin-top: 36px;
      padding-top: 18px;
      border-top: 1px solid var(--border);
      color: var(--muted);
    }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>Runwise</h1>
      <p class="tagline">Runwise helps you check AI agent projects before they go live.</p>
      <p class="tagline">Runwise 帮你在 AI Agent 项目上线前先做一次本地检查。</p>
      <div class="meta-grid">
        ${headerMetrics}
      </div>
    </header>

    <section class="section" aria-labelledby="score-title">
      <h2 id="score-title">Score overview / 评分概览</h2>
      <div class="metric-grid">
        ${scoreMetrics}
      </div>
    </section>

    <section class="section" aria-labelledby="rules-title">
      <h2 id="rules-title">Rule Summary / 规则摘要</h2>
      <div class="rule-grid">
        ${ruleMetrics}
      </div>
    </section>

    <section class="section" aria-labelledby="category-title">
      <h2 id="category-title">Category Scores / 分类评分</h2>
      ${renderCategoryScores(report.summary.categoryScores)}
    </section>

    <section class="section" aria-labelledby="ecosystems-title">
      <h2 id="ecosystems-title">Detected Ecosystems / 检测到的生态</h2>
      ${integrationsHtml}
    </section>

    <section class="section" aria-labelledby="fix-first-title">
      <h2 id="fix-first-title">What to fix first / 优先修复项</h2>
      ${fixFirstHtml}
    </section>

    <section class="section" aria-labelledby="findings-title">
      <h2 id="findings-title">Findings / 检查发现</h2>
      ${findingsHtml}
    </section>

    <section class="section" aria-labelledby="files-title">
      <h2 id="files-title">Report Files / 报告文件</h2>
      <p class="detail">These files are generated locally and ignored by git by default.</p>
      <p class="detail">这些文件在本地生成，默认不会被 git 跟踪。</p>
      <p><code>${escapeHtml(jsonReportPath)}</code></p>
      <p><code>${escapeHtml(markdownReportPath)}</code></p>
      <p><code>${escapeHtml(htmlReportPath)}</code></p>
    </section>

    <footer>
      <p>Generated by Runwise. Local-first. No project data is uploaded.</p>
      <p>由 Runwise 生成。本地优先，不上传项目数据。</p>
    </footer>
  </main>
</body>
</html>`;
}

export const formatDoctorReportJson = renderJsonReport;
export const formatDoctorReportMarkdown = renderMarkdownReport;

function withReportFiles(
  report: RunwiseDoctorReport,
  options: Required<ReportRenderOptions>
): RunwiseDoctorReport {
  return {
    ...report,
    reportFiles: {
      json: formatReportPath(options.cwd, options.jsonPath, ".runwise/runwise-report.json"),
      markdown: formatReportPath(options.cwd, options.markdownPath, ".runwise/runwise-report.md"),
      html: formatReportPath(options.cwd, options.htmlPath, ".runwise/runwise-report.html")
    }
  };
}

function formatFindingMarkdown(finding: RunwiseFinding): string[] {
  const lines = [
    "",
    `#### ${escapeMarkdown(finding.title)} / ${escapeMarkdown(finding.titleZh)}`,
    "",
    `- ID: \`${finding.id}\``,
    finding.ruleId ? `- Rule ID: \`${finding.ruleId}\`` : undefined,
    `- Category: \`${formatCategory(finding.category)}\``,
    `- Severity: \`${finding.severity}\``,
    `- Blocking: ${finding.blocking === true ? "yes" : "no"}`
  ].filter((line): line is string => line !== undefined);

  if (finding.file) {
    lines.push(`- File: \`${finding.file}\``);
  }

  lines.push(
    `- Message: ${escapeMarkdown(finding.message)}`,
    `- 中文说明: ${escapeMarkdown(finding.messageZh)}`,
    `- Recommendation: ${escapeMarkdown(finding.recommendation)}`,
    `- 中文建议: ${escapeMarkdown(finding.recommendationZh)}`
  );

  return lines;
}

function formatIntegrationsMarkdown(report: RunwiseDoctorReport): string[] {
  const integrations = report.integrations?.detected ?? [];

  if (integrations.length === 0) {
    return ["No ecosystem signals detected. / 未检测到生态信号。"];
  }

  const lines = [
    "| Ecosystem | Strength | Signals | Recommendation |",
    "| --- | --- | --- | --- |"
  ];

  for (const integration of integrations) {
    const signals = integration.signals.map(escapeMarkdown).join("<br>");
    const recommendation = integration.recommendations
      .map((item, index) => {
        const zh = integration.recommendationsZh[index];
        return zh ? `${item} / ${zh}` : item;
      })
      .map(escapeMarkdown)
      .join("<br>");

    lines.push(
      `| ${escapeMarkdown(integration.name)} / ${escapeMarkdown(integration.nameZh)} | ${integration.strength} | ${signals} | ${recommendation} |`
    );
  }

  return lines;
}

function formatReplayTimeline(summary: RunwiseTraceReplaySummary): string[] {
  if (summary.steps.length === 0) {
    return ["No steps recorded. / 未记录 step。"];
  }

  return summary.steps.map((step) => {
    const duration = step.durationMs === undefined ? "" : `, ${formatDuration(step.durationMs)}`;
    return `${step.index + 1}. [${step.type}] ${escapeMarkdown(step.summary)} / ${escapeMarkdown(step.summaryZh)} (risk: ${step.risk}, status: ${step.status}${duration})`;
  });
}

function formatReplayErrors(summary: RunwiseTraceReplaySummary): string[] {
  if (summary.errors.count === 0) {
    return ["No error steps were recorded. / 未记录错误步骤。"];
  }

  return summary.errors.messages.map((message) => `- ${escapeMarkdown(message)}`);
}

function formatReplayRecommendations(summary: RunwiseTraceReplaySummary): string[] {
  if (summary.recommendations.length === 0) {
    return ["No replay recommendations were generated. / 暂无复盘建议。"];
  }

  return summary.recommendations.map(
    (recommendation) =>
      `- ${escapeMarkdown(recommendation.message)} / ${escapeMarkdown(recommendation.messageZh)}`
  );
}

function formatEvalInput(input: unknown): string[] {
  if (input === undefined) {
    return ["No input recorded. / 未记录输入。"];
  }

  const serialized = JSON.stringify(input, null, 2);
  if (serialized.length > 1200) {
    return [
      "Input was recorded in the source trace. Inspect the JSON eval file for the full structured input.",
      "",
      "源 trace 中记录了输入。请查看 JSON eval 文件获取完整结构化输入。"
    ];
  }

  return ["```json", serialized, "```"];
}

function formatBilingualList(english: string[], chinese: string[]): string[] {
  const maxLength = Math.max(english.length, chinese.length);
  const lines: string[] = [];

  for (let index = 0; index < maxLength; index += 1) {
    const englishText = english[index];
    const chineseText = chinese[index];

    if (englishText && chineseText) {
      lines.push(`- ${escapeMarkdown(englishText)} / ${escapeMarkdown(chineseText)}`);
      continue;
    }

    if (englishText) {
      lines.push(`- ${escapeMarkdown(englishText)}`);
      continue;
    }

    if (chineseText) {
      lines.push(`- ${escapeMarkdown(chineseText)}`);
    }
  }

  return lines.length > 0 ? lines : ["- none"];
}

function formatEvalAssertions(evalCase: RunwiseEvalCase): string[] {
  if (evalCase.assertions.length === 0) {
    return ["- none"];
  }

  return evalCase.assertions.map((assertion) => {
    const value = assertion.value ? ` (value: \`${escapeMarkdown(assertion.value)}\`)` : "";
    return `- \`${assertion.type}\`: ${escapeMarkdown(assertion.description)} / ${escapeMarkdown(assertion.descriptionZh)}${value}`;
  });
}

function renderYamlValue(value: unknown, indent: number): string {
  const spacing = " ".repeat(indent);

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return `${spacing}[]`;
    }

    return value
      .map((item) => {
        if (isYamlScalar(item)) {
          return `${spacing}- ${formatYamlScalar(item)}`;
        }

        return `${spacing}-\n${renderYamlValue(item, indent + 2)}`;
      })
      .join("\n");
  }

  if (isRecord(value)) {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    if (entries.length === 0) {
      return `${spacing}{}`;
    }

    return entries
      .map(([key, item]) => {
        if (isYamlScalar(item)) {
          return `${spacing}${key}: ${formatYamlScalar(item)}`;
        }

        return `${spacing}${key}:\n${renderYamlValue(item, indent + 2)}`;
      })
      .join("\n");
  }

  return `${spacing}${formatYamlScalar(value)}`;
}

function isYamlScalar(value: unknown): boolean {
  return (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function formatYamlScalar(value: unknown): string {
  if (value === null) {
    return "null";
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  return JSON.stringify(String(value));
}

function renderFindingsBySeverity(findings: RunwiseFinding[]): string {
  if (findings.length === 0) {
    return `<div class="empty-state">No findings. Keep the current readiness baseline healthy.<br>暂无 finding，请保持当前就绪度基线。</div>`;
  }

  return SEVERITY_ORDER.map((severity) => {
    const severityFindings = getFindingsBySeverity(findings, severity);
    if (severityFindings.length === 0) {
      return "";
    }

    return `<h3>${capitalize(severity)}</h3><div class="finding-list">${severityFindings.map(renderFindingCard).join("\n")}</div>`;
  })
    .filter(Boolean)
    .join("\n");
}

function renderIntegrations(report: RunwiseDoctorReport): string {
  const integrations = report.integrations?.detected ?? [];

  if (integrations.length === 0) {
    return `<div class="empty-state">No ecosystem signals detected.<br>未检测到生态信号。</div>`;
  }

  return `<div class="finding-list">${integrations
    .map((integration) => {
      const signals = integration.signals
        .slice(0, 5)
        .map((signal) => `<li>${escapeHtml(signal)}</li>`)
        .join("\n");
      const recommendations = integration.recommendations
        .map((recommendation, index) => {
          const recommendationZh = integration.recommendationsZh[index] ?? "";
          return `<li>${escapeHtml(recommendation)}<br><span class="detail">${escapeHtml(recommendationZh)}</span></li>`;
        })
        .join("\n");

      return `<article class="finding">
  <div class="finding-head">
    <span class="badge">${escapeHtml(integration.strength)}</span>
    <span class="badge">${escapeHtml(integration.id)}</span>
  </div>
  <h3>${escapeHtml(integration.name)} / ${escapeHtml(integration.nameZh)}</h3>
  <p class="detail">Local heuristic detection only. No framework execution or external API call was performed.</p>
  <div class="finding-grid">
    <div>
      <p><strong>Signals</strong></p>
      <ul>${signals}</ul>
    </div>
    <div>
      <p><strong>Recommendations / 建议</strong></p>
      <ul>${recommendations}</ul>
    </div>
  </div>
</article>`;
    })
    .join("\n")}</div>`;
}

function renderFindingCard(finding: RunwiseFinding): string {
  const ruleId = finding.ruleId
    ? `<span class="badge">Rule: ${escapeHtml(finding.ruleId)}</span>`
    : "";
  const file = finding.file
    ? `<p class="detail">File: <code>${escapeHtml(finding.file)}</code></p>`
    : "";
  const blocking = finding.blocking === true
    ? `<span class="badge badge-blocking">Blocking</span>`
    : "";

  return `<article class="finding">
  <div class="finding-head">
    <span class="badge badge-${finding.severity}">${finding.severity}</span>
    <span class="badge">${escapeHtml(finding.category)}</span>
    ${ruleId}
    ${blocking}
  </div>
  <h3>${escapeHtml(finding.title)}</h3>
  <p class="detail">${escapeHtml(finding.titleZh)}</p>
  ${file}
  <div class="finding-grid">
    <div>
      <p><strong>Message</strong></p>
      <p>${escapeHtml(finding.message)}</p>
      <p><strong>Recommendation</strong></p>
      <p>${escapeHtml(finding.recommendation)}</p>
    </div>
    <div>
      <p><strong>中文说明</strong></p>
      <p>${escapeHtml(finding.messageZh)}</p>
      <p><strong>中文建议</strong></p>
      <p>${escapeHtml(finding.recommendationZh)}</p>
    </div>
  </div>
</article>`;
}

function renderCategoryScores(
  categoryScores: RunwiseDoctorReport["summary"]["categoryScores"]
): string {
  if (!categoryScores || Object.keys(categoryScores).length === 0) {
    return `<div class="empty-state">Category scoring will be refined in a later report loop.<br>分类评分将在后续报告 loop 中继续细化。</div>`;
  }

  return `<div class="category-grid">${Object.entries(categoryScores)
    .map(([category, score]) => renderMetric(formatCategory(category as RunwiseCategory), `${score}/100`))
    .join("\n")}</div>`;
}

function renderMetric(label: string, value: string, escapeValue = true, className = ""): string {
  const classes = className ? `metric ${className}` : "metric";
  return `<div class="${classes}"><div class="metric-label">${escapeHtml(label)}</div><div class="metric-value">${escapeValue ? escapeHtml(value) : value}</div></div>`;
}

function formatFixFirstMarkdown(findings: RunwiseFinding[]): string[] {
  const priorityFindings = getPriorityFindings(findings).slice(0, 5);

  if (priorityFindings.length === 0) {
    return [
      "No blocking, critical, or high-priority findings were found. Review medium and low findings when you have time.",
      "",
      "没有发现 blocking、critical 或 high 级别问题。你可以在有时间时继续查看 medium 和 low 级别建议。"
    ];
  }

  return [
    "| Priority | Severity | Category | Finding | Recommendation |",
    "| ---: | --- | --- | --- | --- |",
    ...priorityFindings.map((finding, index) => {
      const severity = finding.blocking === true
        ? `blocking · ${finding.severity}`
        : finding.severity;
      return `| ${index + 1} | ${severity} | ${escapeMarkdown(finding.category)} | ${escapeMarkdown(finding.title)}<br>${escapeMarkdown(finding.titleZh)} | ${escapeMarkdown(finding.recommendation)}<br>${escapeMarkdown(finding.recommendationZh)} |`;
    })
  ];
}

function formatCategoryScoresMarkdown(
  categoryScores: RunwiseDoctorReport["summary"]["categoryScores"]
): string[] {
  if (!categoryScores || Object.keys(categoryScores).length === 0) {
    return [
      "Category scoring is not available in this report.",
      "",
      "此报告暂未提供分类评分。"
    ];
  }

  return [
    "| Category | Score |",
    "| --- | ---: |",
    ...Object.entries(categoryScores).map(
      ([category, score]) => `| ${escapeMarkdown(formatCategory(category as RunwiseCategory))} | ${score}/100 |`
    )
  ];
}

function getPriorityFindings(findings: RunwiseFinding[]): RunwiseFinding[] {
  return [...findings]
    .filter(
      (finding) =>
        finding.blocking === true ||
        finding.severity === "critical" ||
        finding.severity === "high" ||
        finding.severity === "medium"
    )
    .sort(compareFindingsByPriority);
}

function compareFindingsByPriority(a: RunwiseFinding, b: RunwiseFinding): number {
  if (a.blocking === true && b.blocking !== true) {
    return -1;
  }
  if (a.blocking !== true && b.blocking === true) {
    return 1;
  }

  return SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity);
}

function getFindingsBySeverity(
  findings: RunwiseFinding[],
  severity: RunwiseSeverity
): RunwiseFinding[] {
  return findings.filter((finding) => finding.severity === severity);
}

function formatReportPath(
  cwd: string | undefined,
  reportPath: string | undefined,
  fallback: string
): string {
  if (!reportPath) {
    return fallback;
  }

  if (!cwd) {
    return reportPath;
  }

  const relativePath = path.relative(cwd, reportPath);
  return relativePath.startsWith("..") ? reportPath : relativePath;
}

function formatCategory(category: RunwiseCategory): string {
  return category;
}

function capitalize(value: string): string {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function formatDuration(durationMs: number | undefined): string {
  if (durationMs === undefined) {
    return "not recorded";
  }

  return `${durationMs}ms`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
