import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { get } from "node:http";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cliBin = resolve(rootDir, "node_modules/.bin/runwise");
const expectedRuleCount = 15;

const governanceFiles = [
  "PROJECT_CONSTITUTION.md",
  "PRODUCT_SPEC.md",
  "ARCHITECTURE.md",
  "CODEX_LOOP_PROTOCOL.md",
  "ROADMAP.md",
  "RUN_STATE.md",
  "DECISION_LOG.md",
  "NON_GOALS.md"
];

const fixtureRoots = [];
const viewerProcesses = [];

try {
  const helpRun = runCli(["--help"]);
  assert.equal(helpRun.status, 0);
  assert.match(helpRun.stdout, /Runwise/);
  assert.match(helpRun.stdout, /doctor\s+Scan the current project and generate local reports/);
  assert.match(helpRun.stdout, /view\s+Open a local dashboard viewer/);

  const missingReportProject = createFixtureProject();
  const missingReportRun = runCli(["view"], missingReportProject);
  assert.equal(missingReportRun.status, 1);
  assert.match(missingReportRun.stderr, /No local report found/);
  assert.match(missingReportRun.stderr, /\.runwise\/runwise-report\.json/);
  assert.match(missingReportRun.stderr, /pnpm exec runwise doctor/);

  const base = createFixtureProject();
  const baseRun = runDoctor(base);

  assert.match(baseRun.stdout, /Runwise Doctor/);
  assert.match(baseRun.stdout, /Rules:/);
  assert.match(baseRun.stdout, /Reports:/);
  assert.match(baseRun.stdout, /\.runwise\/runwise-report\.html/);
  assert.equal(existsSync(baseRun.jsonPath), true, "JSON report should be generated");
  assert.equal(existsSync(baseRun.markdownPath), true, "Markdown report should be generated");
  assert.equal(existsSync(baseRun.htmlPath), true, "HTML report should be generated");

  assert.equal(baseRun.report.tool, "runwise");
  assert.equal(baseRun.report.command, "doctor");
  assert.equal(baseRun.report.scannedPath, base);
  assert.equal(baseRun.report.rules.total, expectedRuleCount);
  assert.equal(
    baseRun.report.rules.passed +
      baseRun.report.rules.failed +
      baseRun.report.rules.notApplicable,
    baseRun.report.rules.total
  );
  assert.equal(baseRun.report.checks.governanceFilesDetected, true);
  assert.equal(baseRun.report.summary.overallScore >= 0, true);
  assert.equal(baseRun.report.summary.overallScore <= 100, true);
  assert.ok(baseRun.report.summary.categoryScores, "Category scores should be included");
  assert.deepEqual(baseRun.report.reportFiles, {
    json: ".runwise/runwise-report.json",
    markdown: ".runwise/runwise-report.md",
    html: ".runwise/runwise-report.html"
  });

  assertFinding(baseRun.report, {
    ruleId: "evals.coverage_present",
    severity: "medium",
    blocking: false
  });
  assertFinding(baseRun.report, {
    ruleId: "tracing.coverage_present",
    severity: "medium",
    blocking: false
  });

  assert.match(baseRun.markdown, /## Rule Summary/);
  assert.match(baseRun.markdown, /Blocking findings/);
  assert.match(baseRun.markdown, /## What to Fix First/);
  assert.match(baseRun.markdown, /## Report Files/);
  assert.match(baseRun.markdown, /No eval coverage detected/);
  assert.match(baseRun.markdown, /未检测到评测覆盖/);
  assert.match(baseRun.markdown, /\.runwise\/runwise-report\.json/);
  assert.match(baseRun.markdown, /\.runwise\/runwise-report\.md/);
  assert.match(baseRun.markdown, /\.runwise\/runwise-report\.html/);

  assert.match(baseRun.html, /<h1>Runwise<\/h1>/);
  assert.match(baseRun.html, /Local-first AI readiness, tracing, replay and eval toolkit/);
  assert.match(baseRun.html, /面向 AI 项目的本地优先上线体检、运行审计、失败回放与评测生成工具/);
  assert.match(baseRun.html, /Overall score/);
  assert.match(baseRun.html, /Score and Severity Summary/);
  assert.match(baseRun.html, /Rule Summary/);
  assert.match(baseRun.html, /What to Fix First/);
  assert.match(baseRun.html, /Findings/);
  assert.match(baseRun.html, /medium/);
  assert.match(baseRun.html, /No eval coverage detected/);
  assert.match(baseRun.html, /Generated by Runwise/);
  assert.match(baseRun.html, /<style>/);
  assert.doesNotMatch(baseRun.html, /<script\b/i);
  assert.doesNotMatch(baseRun.html, /<link\b/i);
  assert.doesNotMatch(baseRun.html, /https?:\/\//i);
  assert.doesNotMatch(baseRun.html, /\[object Object\]/);
  assert.doesNotMatch(baseRun.html, /TODO|PLACEHOLDER/i);

  await assertViewerServer(base);

  const missingConstitution = createFixtureProject({
    omitGovernance: ["PROJECT_CONSTITUTION.md"]
  });
  const missingConstitutionRun = runDoctor(missingConstitution);
  assertFinding(missingConstitutionRun.report, {
    ruleId: "governance.constitution_present",
    severity: "high",
    blocking: true
  });
  assert.equal(missingConstitutionRun.report.rules.blocking, 1);

  const missingProtocol = createFixtureProject({
    omitGovernance: ["CODEX_LOOP_PROTOCOL.md"]
  });
  const missingProtocolRun = runDoctor(missingProtocol);
  assertFinding(missingProtocolRun.report, {
    ruleId: "governance.codex_loop_protocol_present",
    severity: "high",
    blocking: true
  });
  assert.equal(missingProtocolRun.report.rules.blocking, 1);
} finally {
  for (const child of viewerProcesses) {
    child.kill("SIGTERM");
  }

  for (const fixtureRoot of fixtureRoots) {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
}

console.log("Runwise CLI and viewer tests passed.");

function runCli(args, cwd = rootDir) {
  return spawnSync(cliBin, args, {
    cwd,
    encoding: "utf8",
    shell: process.platform === "win32"
  });
}

function createFixtureProject(options = {}) {
  const projectRoot = realpathSync(mkdtempSync(join(tmpdir(), "runwise-doctor-")));
  fixtureRoots.push(projectRoot);

  mkdirSync(join(projectRoot, "apps"), { recursive: true });
  mkdirSync(join(projectRoot, "packages"), { recursive: true });

  writeFileSync(
    join(projectRoot, "package.json"),
    JSON.stringify(
      {
        name: "runwise-test-fixture",
        private: true,
        type: "module"
      },
      null,
      2
    )
  );
  writeFileSync(join(projectRoot, "pnpm-workspace.yaml"), 'packages:\n  - "apps/*"\n  - "packages/*"\n');
  writeFileSync(join(projectRoot, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
  writeFileSync(
    join(projectRoot, "tsconfig.base.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext"
        }
      },
      null,
      2
    )
  );

  const omittedGovernance = new Set(options.omitGovernance ?? []);
  for (const file of governanceFiles) {
    if (!omittedGovernance.has(file)) {
      writeFileSync(join(projectRoot, file), `# ${file}\n`);
    }
  }

  return projectRoot;
}

function runDoctor(projectRoot) {
  const result = runCli(["doctor"], projectRoot);

  assert.equal(
    result.status,
    0,
    `runwise doctor failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`
  );

  const reportDir = join(projectRoot, ".runwise");
  const jsonPath = join(reportDir, "runwise-report.json");
  const markdownPath = join(reportDir, "runwise-report.md");
  const htmlPath = join(reportDir, "runwise-report.html");
  const report = JSON.parse(readFileSync(jsonPath, "utf8"));
  const markdown = readFileSync(markdownPath, "utf8");
  const html = readFileSync(htmlPath, "utf8");

  return {
    stdout: result.stdout,
    jsonPath,
    markdownPath,
    htmlPath,
    report,
    markdown,
    html
  };
}

async function assertViewerServer(projectRoot) {
  const child = spawn(cliBin, ["view", "--port", "0"], {
    cwd: projectRoot,
    stdio: ["ignore", "pipe", "pipe"],
    shell: process.platform === "win32"
  });
  viewerProcesses.push(child);

  const { stdout, url } = await waitForViewerUrl(child);
  assert.match(stdout, /Runwise Viewer/);
  assert.match(stdout, /Loaded report:/);
  assert.match(stdout, /\.runwise\/runwise-report\.json/);
  assert.match(stdout, /Local dashboard:/);

  const dashboard = await httpGet(url);
  assert.equal(dashboard.statusCode, 200);
  assert.match(dashboard.body, /<h1>Runwise<\/h1>/);
  assert.match(dashboard.body, /Local-first AI readiness, tracing, replay and eval toolkit/);
  assert.match(dashboard.body, /Runwise is local-first\. This viewer reads your generated report file and does not send data anywhere\./);
  assert.match(dashboard.body, /Runwise 采用本地优先设计。此查看器只读取本地生成的报告文件，不会上传数据。/);
  assert.match(dashboard.body, /Overall score/);
  assert.match(dashboard.body, /Rule Summary/);
  assert.match(dashboard.body, /Findings Explorer/);
  assert.match(dashboard.body, /No eval coverage detected/);

  const reportJson = await httpGet(`${url}/report.json`);
  assert.equal(reportJson.statusCode, 200);
  assert.equal(JSON.parse(reportJson.body).tool, "runwise");

  const health = await httpGet(`${url}/health`);
  assert.equal(health.statusCode, 200);
  assert.equal(JSON.parse(health.body).ok, true);

  child.kill("SIGTERM");
}

function waitForViewerUrl(child) {
  return new Promise((resolve, reject) => {
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      reject(new Error(`Timed out waiting for viewer URL\nstdout:\n${stdout}\nstderr:\n${stderr}`));
    }, 5000);

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
      const match = stdout.match(/http:\/\/localhost:\d+/);
      if (!match) {
        return;
      }

      clearTimeout(timer);
      resolve({ stdout, url: match[0] });
    });

    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });

    child.on("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });

    child.on("exit", (code) => {
      if (!stdout.match(/http:\/\/localhost:\d+/)) {
        clearTimeout(timer);
        reject(new Error(`Viewer exited before URL with code ${code}\nstdout:\n${stdout}\nstderr:\n${stderr}`));
      }
    });
  });
}

function httpGet(url) {
  return new Promise((resolve, reject) => {
    const request = get(url, (response) => {
      let body = "";
      response.setEncoding("utf8");
      response.on("data", (chunk) => {
        body += chunk;
      });
      response.on("end", () => {
        resolve({
          statusCode: response.statusCode,
          body
        });
      });
    });

    request.on("error", reject);
    request.end();
  });
}

function assertFinding(report, expected) {
  const finding = report.findings.find((item) => item.ruleId === expected.ruleId);
  assert.ok(finding, `Expected finding for ${expected.ruleId}`);
  assert.equal(
    finding.severity,
    expected.severity,
    `Expected ${expected.ruleId} severity ${expected.severity}`
  );
  assert.equal(
    finding.blocking === true,
    expected.blocking,
    `Expected ${expected.ruleId} blocking ${expected.blocking}`
  );
}
